<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Услуги RISE: пошив сумок, рюкзаков и папок на заказ, оптовые поставки сумок, рюкзаков и шопперов, брендирование и работа с корпоративными клиентами.");
$APPLICATION->SetPageProperty("title", "Услуги RISE | Пошив и оптовые поставки сумок и рюкзаков");
$APPLICATION->SetTitle("Услуги");
?><? $APPLICATION->IncludeComponent(
	"bitrix:news", 
	"services", 
	[
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => [
			0 => "DETAIL_TEXT",
			1 => "",
		],
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => [
			0 => "LINKED_FAQ",
			1 => "LINKED_MAIN_BANNERS",
			2 => "LINKED_ADVANTAGES",
			3 => "LINKED_IMAGES",
			4 => "SEO_BLOCK",
			5 => "LINKED_TIZZERS",
			6 => "LINKED_STAGES",
			7 => "ADVANTAGES_TITLE",
			8 => "COOPERATION_TITLE",
			9 => "TIZZERS_TITLE",
			10 => "STAGES_TITLE",
			11 => "LINKED_COOPERATION",
			12 => "",
		],
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "13",
		"IBLOCK_TYPE" => "site_content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => [
			0 => "",
			1 => "",
		],
		"LIST_PROPERTY_CODE" => [
			0 => "",
			1 => "",
		],
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"COMPONENT_TEMPLATE" => "services",
		"SEF_FOLDER" => "/services/",
		"TOP_BANNER_IBLOCK_ID" => "",
		"TOP_BANNER_SECTION_ID" => "",
		"FIRST_TIZZERS_IBLOCK_ID" => "",
		"FIRST_TIZZERS_SECTION_ID" => "",
		"FIRST_TIZZERS_TITLE" => "",
		"SECOND_TIZZERS_IBLOCK_ID" => "",
		"SECOND_TIZZERS_SECTION_ID" => "",
		"SECOND_TIZZERS_TITLE" => "",
		"THIRD_TIZZERS_IBLOCK_ID" => "",
		"THIRD_TIZZERS_SECTION_ID" => "",
		"THIRD_TIZZERS_TITLE" => "",
		"FOURTH_TIZZERS_IBLOCK_ID" => "",
		"FOURTH_TIZZERS_SECTION_ID" => "",
		"FOURTH_TIZZERS_TITLE" => "",
		"FAQ_PREVIEW_IBLOCK_ID" => "",
		"FAQ_PREVIEW_SECTION_ID" => "",
		"SEF_URL_TEMPLATES" => [
			"news" => "",
			"section" => "#SECTION_CODE_PATH#/",
			"detail" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
		]
	],
	false
); ?><? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php") ?>